backend/src/backend/blueprints/users/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired



class RegisterUserForm(FlaskForm):
    public_username = StringField(label='Public Username', validators=[DataRequired()])
    private_username = StringField(label='Private Username', validators=[DataRequired()])
    password = StringField(label='Password', validators=[DataRequired()])
    password_match = StringField(label='Re-Enter Password', validators=[DataRequired()])
    submit = SubmitField(label="Submit")


class LoginForm(FlaskForm):
    private_username = StringField(label='Private Username', validators=[DataRequired()])
    password = StringField(label='Password', validators=[DataRequired()])
    submit = SubmitField(label="Submit")

backend/src/backend/blueprints/users/views.py
import os
from flask import (
    Blueprint,
    current_app,
    redirect,
    render_template,
    url_for,
)
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user,
)

from . import forms, queries
from ...extensions import fbcrypt
from ...models.models import db, User
from ...models.queries import load_role
from ...toolbox.helpers import generate_secret_key


users = Blueprint('users', __name__, template_folder="templates/users")


# Route to redirect users who try and access an area they do not have permission for.
# Ex: customers requesting vendor routes
# Also used after login to prevent redundant code. 
@users.route('/invalid-request')
@users.route('/redirect-user')
@login_required
def redirect_user():
    if current_user.is_authenticated:
        if current_user.role.name == "admin":
            return redirect(url_for('admin.home'), code=301)
        elif current_user.role.name == "vendor":
            return redirect(url_for('vendor.home'), code=301)
        else:
            return redirect(url_for('market.index'), code=301)
    else:
        return redirect(url_for('public.index'), code=301)
        

@users.route('/login', methods=['GET', 'POST'])
def login():
    # redirect to the portal homepage if authenticated
    if current_user.is_authenticated:
        return redirect('/redirect-user')
    # login page information
    elements = {
        "title": "Login",
        "market_name": os.environ['MARKET_NAME'],    
    }
    f = forms.LoginForm()
    if f.validate_on_submit():
        u = queries.get_user(db, f.private_username.data)
        print(f"User Pass: {u.password}, Given: {f.password.data}")
        if u and fbcrypt.check_password_hash(u.password, f.password.data):
            login_user(u)
            return redirect('/redirect-user')
        else:
            flash('Invalid credentials.', 'danger')
    return render_template("login.html", elements=elements, form=f)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('public.index'))


# Register customer
@users.route("/register-customer", methods=["GET", "POST"])
def register_customer():
    elements = {
        "title": "Register Market Account",
        "market_name": os.environ['MARKET_NAME'],    
    }
    form = forms.RegisterUserForm()
    if form.validate_on_submit():
        if form.password.data == form.password_match.data: # and queries.check_unique_usernames(db, form.public_username.data, form.private_username.data)
            u = User(
                role_id=load_role(db, "customer").id,
                public_username=form.public_username.data,
                private_username=form.private_username.data,
                password=fbcrypt.generate_password_hash(form.password.data),
                secret_key=generate_secret_key(),
            )
            # Need a try and excpet block here to handle a transaction that has already begun
            # Error: sqlalchemy.exc.InvalidRequestError
            # Do I even need to have a with db.session.begin() here? 
            # Need to clean this up before moving into the forum.
            try:
                db.session.add(u)
                db.session.commit()
            except Exception as e:
                db.session.rollback()
                print(e)
            return redirect(url_for("users.login"))
        else:
            flash("Passwords must match.")
            return render_template("register_customer.html", elements=elements, form=form)
    return render_template("register_customer.html", elements=elements, form=form)


# New vendors 
@users.route("/register-vendor", methods=["GET", "POST"])
def register_vendor():
    elements = {
        "title": "Register Vendor Account",
        "market_name": os.environ['MARKET_NAME'],    
    }
    form = forms.RegisterUserForm()
    if form.validate_on_submit():
        if form.password.data == form.password_match.data:
            u = User(
                role_id=load_role(db, "vendor").id,
                public_username=form.public_username.data,
                private_username=form.private_username.data,
                password=fbcrypt.generate_password_hash(form.password.data),
                secret_key=generate_secret_key(),
            )    
            try:
                db.session.add(u)
                db.session.commit()
            except Exception as e:
                db.session.rollback()
                print(e)
            return redirect(url_for("users.login"))
        else:
            flash("Passwords must match.")
            return render_template("register_vendor.html", elements=elements, form=form)
    return render_template("register_vendor.html", elements=elements, form=form)



# Post login welcome screen. Show actions available to user.
@users.route('/welcome')
@login_required
def welcome():
    return render_template('welcome.html')
    

backend/src/backend/blueprints/users/templates/users/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if elements['title'] %}
      <title>{{ elements['title'] }}</title>
    {% else %}
      <title>Malice Manor</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block staticFiles %}
    {% endblock staticFiles %}
  </head>
  <body>
      <header>
          {% block navbar %}
          {% endblock navbar%}
      </header>

      <main style="height: 100vh;">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block main %}
          {% endblock main %}
      </main>

      <footer>
          {% block footer %}
          {% endblock footer %}
      </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

backend/src/backend/blueprints/users/templates/users/login.html
{% extends "base.html" %}

{% block navbar %}
<!-- top navbar start -->
<nav class="navbar navbar-expand-lg verdigris-backdrop" >
  <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('public.index') }}">{{ elements['market_name'] }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('users.login') }}">Login</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Create Account
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{ url_for('users.register_customer') }}">Register Account</a></li>
                <li><a class="dropdown-item" href="{{ url_for('users.register_vendor') }}">Vendor Application</a></li>
              </ul>
            </li>
      </div>
  </div>
</nav>
{% endblock navbar %}

{% block main %}
<div class="container-sm mt-4">
    <div class="card">
        <div class="card-header align-items-center text-center">
          <h5>Welcome Back</h5>
        </div>
        <div class="card-body">
            <form method="POST">
                {{ form.csrf_token }}    
                <fieldset>
                    <legend class="border-bottom mb-4">{{ legend }}</legend>
                    <div class="form-group mb-3">
                        {{ form.private_username.label(class='form-control-label') }}
                        {% if form.private_username.errors %}
                            {{ form.private_username.label(class='form-control form-control-md is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.private_username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.private_username(class='form-control form-control-md')}}
                        {% endif %}
                    </div>
                    <div class="form-group mb-3">
                        {{ form.password.label(class='form-control-label') }}
                        {% if form.password.errors %}
                            {{ form.password.label(class='form-control form-control-md is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class='form-control form-control-md')}}
                        {% endif %}
                    </div>
                    <div class="form-group text-center mb-3">
                        {{ form.submit(class='btn btn-primary signature-color-button', style='width: 75%;') }}
                    </div>
                </fieldset>
            </form>
        </div>
      </div>
</div>
{% endblock main %}

backend/src/backend/blueprints/users/templates/users/register_customer.html
{% extends "base.html" %}

{% block staticFiles %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
{% endblock staticFiles %}


{% block navbar %}
<!-- top navbar start -->
<nav class="navbar navbar-expand-lg verdigris-backdrop" >
  <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('public.index') }}">{{ elements['market_name'] }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{{ url_for('users.login') }}">Login</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Create Account
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{ url_for('users.register_customer') }}">Register Account</a></li>
                <li><a class="dropdown-item" href="{{ url_for('users.register_vendor') }}">Vendor Application</a></li>
              </ul>
            </li>
      </div>
  </div>
</nav>
{% endblock navbar %}



{% block main %}
<div class="container-sm mt-4">
    <div class="card">
        <div class="card-header align-items-center text-center">
          <h5>Register Market Account</h5>
        </div>
        <div class="card-body">
            <form method="POST">
                {{ form.csrf_token }}    
                <fieldset>
                    <legend class="border-bottom mb-4">{{ legend }}</legend>
                    <div class="form-group mb-3">
                        {{ form.public_username.label(class='form-control-label') }}
                        {% if form.public_username.errors %}
                            {{ form.public_username.label(class='form-control form-control-md is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.public_username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.public_username(class='form-control form-control-md')}}
                        {% endif %}
                    </div>
                    
                    <div class="form-group mb-3">
                        {{ form.private_username.label(class='form-control-label') }}
                        {% if form.private_username.errors %}
                            {{ form.private_username.label(class='form-control form-control-md is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.private_username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.private_username(class='form-control form-control-md')}}
                        {% endif %}
                    </div>

                    <div class="form-group mb-3">
                        {{ form.password.label(class='form-control-label') }}
                        {% if form.password.errors %}
                            {{ form.password.label(class='form-control form-control-md is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class='form-control form-control-md')}}
                        {% endif %}
                    </div>
                    
                    <div class="form-group mb-3">
                        {{ form.password_match.label(class='form-control-label') }}
                        {% if form.password_match.errors %}
                            {{ form.password_match.label(class='form-control form-control-md is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.password_match.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password_match(class='form-control form-control-md')}}
                        {% endif %}
                    </div>

                    <div class="form-group text-center mb-3">
                        {{ form.submit(class='btn btn-primary signature-color-button', style='width: 75%;') }}
                    </div>
                </fieldset>
            </form>
        </div>
      </div>
</div>


{% endblock main %}

backend/src/backend/blueprints/users/templates/users/register_vendor.html
{% extends "base.html" %}

{% block staticFiles %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
{% endblock staticFiles %}


{% block navbar %}
<!-- top navbar start -->
<nav class="navbar navbar-expand-lg verdigris-backdrop" >
  <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('public.index') }}">{{ elements['market_name'] }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{{ url_for('users.login') }}">Login</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Create Account
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{ url_for('users.register_customer') }}">Register Account</a></li>
                <li><a class="dropdown-item" href="{{ url_for('users.register_vendor') }}">Vendor Application</a></li>
              </ul>
            </li>
      </div>
  </div>
</nav>
{% endblock navbar %}



{% block main %}
<div class="container-sm mt-4">
    <div class="card">
        <div class="card-header align-items-center text-center">
          <h5>Register Vendor Account</h5>
        </div>
        <div class="card-body">
            <form method="POST">
                {{ form.csrf_token }}    
                <fieldset>
                    <legend class="border-bottom mb-4">{{ legend }}</legend>
                    <div class="form-group mb-3">
                        {{ form.public_username.label(class='form-control-label') }}
                        {% if form.public_username.errors %}
                            {{ form.public_username.label(class='form-control form-control-md is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.public_username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.public_username(class='form-control form-control-md')}}
                        {% endif %}
                    </div>
                    
                    <div class="form-group mb-3">
                        {{ form.private_username.label(class='form-control-label') }}
                        {% if form.private_username.errors %}
                            {{ form.private_username.label(class='form-control form-control-md is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.private_username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.private_username(class='form-control form-control-md')}}
                        {% endif %}
                    </div>

                    <div class="form-group mb-3">
                        {{ form.password.label(class='form-control-label') }}
                        {% if form.password.errors %}
                            {{ form.password.label(class='form-control form-control-md is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class='form-control form-control-md')}}
                        {% endif %}
                    </div>
                    
                    <div class="form-group mb-3">
                        {{ form.password_match.label(class='form-control-label') }}
                        {% if form.password_match.errors %}
                            {{ form.password_match.label(class='form-control form-control-md is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.password_match.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password_match(class='form-control form-control-md')}}
                        {% endif %}
                    </div>

                    <div class="form-group text-center mb-3">
                        {{ form.submit(class='btn btn-primary signature-color-button', style='width: 75%;') }}
                    </div>
                </fieldset>
            </form>
        </div>
      </div>
</div>


{% endblock main %}