backend/src/backend/blueprints/crm/forms.py
from flask_wtf import FlaskForm

from wtforms import EmailField, StringField, SelectField
from wtforms.validators import DataRequired, Email

class CreateCustomer(FlaskForm):
    company = StringField(label="Company", validators=[DataRequired(message='Company name required.')])
    street = StringField(label="Street", validators=[DataRequired(message='Street address required.')])
    street2 = StringField(label="Street 2")
    city = StringField(label="City", validators=[DataRequired(message='City required.')])
    state = SelectField(label="State", validators[DataRequired(message='State required.')])
    zip_code = StringField(label="Zip Code", validators=[DataRequired(message='Zip code required.')])


class CreateContact(FlaskForm):
    name = StringField(label='Name', validators=[DataRequired(message='Contact name required.')])
    phone = StringField(label='Phone', validators=[DataRequired(message='Phone number required.')])
    email = EmailField(label='Email', validators=[Email(message='Invalid email address.')])
    company = SelectField(label="Company")

backend/src/backend/blueprints/crm/routes.py
from flask import Blueprint, current_app, render_template, redirect, url_for

from . import queries

from ...models.models import db
from ...models.models import Customer, Contact


# we are assuming crm stands for customer relationship management
crm = Blueprint(
    'crm', __name__, template_folder='templates/crm', url_prefix='/crm')


""" Test Routes """
from ...models.tests.populate import populate_customers, populate_contacts

@crm.route("/insert")
def insert():
    with current_app.app_context():
        #populate_customers(db)
        #populate_contacts(db)
        from . import populate
        populate.populate_notes(db)
    return redirect(url_for('crm.customers'))


@crm.route("/list-contacts")
def list_contacts():
    customers = queries.customers(db)
    contacts = queries.contacts(db)
    for customer in customers:
        print("\n\n{}".format(customer.company))
        for contact in contacts:
            if contact.company_id == customer.id:
                print("{} - {}".format(contact.name, contact.phone))
    return redirect(url_for('crm.home'))


""" CRM Routes """
@crm.route("/")
def home():
    
    elements = {
        'title': 'United-Journal',
        'top_customers': None,
    }
    return render_template('home.html', elements=elements)


@crm.route("/customers")
def customers():
    elements = {
        'title': 'Customers',
    }
    customers = queries.customers(db)
    print(customers)
    return render_template('customers.html', elements=elements, customers=customers)


@crm.route("/customers/create-customer")
def create_customer():
    pass


@crm.route("/feed")
def feed():
    return render_template('feed.html')


@crm.route('/customer-inquiry')
def customer_inquiry():
    return render_template('customer_inquiry.html')


@crm.route('/new_customer')
def new_customer():
    return render_template('new_customer.html')


@crm.route('/customers/<int:id>')
def customer(id):
    customer = db.get_or_404(Customer, id)
    return customer.company


@crm.route('/customers/<int:id>/notes/create', methods=['GET', 'POST'])
def create_customer_note(id):
    customer = db.get_or_404(Customer, id)
    # form = CreateCustomerNoteForm()
    return "creating customer note"


@crm.route('/customers/<int:customer_id>/notes')
def customer_notes(customer_id):
    customer = db.get_or_404(Customer, customer_id)
    notes = queries.customer_notes(db, customer)
    if len(notes) == 0:
        return "No notes"
    return "Customer: {} has {} notes".format(customer.company, len(notes))


    
@crm.route('/customers/<int:customer_id>/notes/<int:note_id>/view')
def customer_note(customer_id, note_id):
    customer = db.get_or_404(Customer, customer_id)
    note = queries.customer_note(db, customer, note_id)
    return note.title

backend/src/backend/blueprints/crm/templates/crm/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
        {% if elements['title'] %}
            <title>{{ elements['title'] }}</title>
        {% else %}
            <title>United-Journal</title>
        {% endif %}
    </head>
    <body>
        <header>
            {% block navbar %} {% endblock navbar %}
        </header>

        <br>

        <main  style="height: 100vh;">
            {% block main %} {% endblock main %}
        </main>
        
        
        <br></br>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <p>&copy; 2023 Logan Lee Development Inc. All rights reserved.</p>
                    </div>
                </div>
            </div>
        </footer>
    </body>


</html>

backend/src/backend/blueprints/crm/templates/crm/customers.html
{% extends 'base.html' %}

{% block navbar %}
<nav class="navbar navbar-expand-lg color">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">United-Journal</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('sales.home') }}">Home</a>
                </li>
                
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Customers
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{{ url_for('crm.customer_inquiry') }}">Customer Inquiry</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('crm.new_customer') }}">New Customer</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Customer Reports</a></li>
                      <li><a class="dropdown-item" href="#">Customer Templates</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Orders
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{{ url_for('orders.create') }}">New Order</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('orders.index') }}">Order Inquiry</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Order Templates</a></li>
                      <li><a class="dropdown-item" href="#">Customer Templates</a></li>
                    </ul>
                </li>
                
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Purchasing
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{{ url_for('purchasing.index') }}">Purchasing</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('purchasing.purchase_orders') }}">Purchase Orders</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{{ url_for('purchasing.vendors') }}">Vendors</a></li>
                      <li><a class="dropdown-item" href="#">Explore Stock</a></li>
                    </ul>
                </li>

            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>


{% endblock navbar %}




{% block main %}
<div class="container-lg">
    <div class="card">
        <div class="card-body">
            This is some text within a card body.
        </div>
    </div>
</div>
<br>
<div class="container-lg" >
    <div class="card">
        <div class="card-header">
        Customers
        </div>
        <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            {% for c in elements['customers'] %}
                <h3>{{ c.company }}</h3>
            {% endfor %}
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
</div>
{% endblock main %} 

backend/src/backend/blueprints/crm/templates/crm/home.html
{% extends 'base.html' %}

{% block navbar %}
<nav class="navbar navbar-expand-lg color">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">United-Journal</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('sales.home') }}">Home</a>
                </li>
                
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Customers
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{{ url_for('crm.customer_inquiry') }}">Customer Inquiry</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('crm.new_customer') }}">New Customer</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Customer Reports</a></li>
                      <li><a class="dropdown-item" href="#">Customer Templates</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Orders
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{{ url_for('orders.create') }}">New Order</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('orders.index') }}">Order Inquiry</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Order Templates</a></li>
                      <li><a class="dropdown-item" href="#">Customer Templates</a></li>
                    </ul>
                </li>
                
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Purchasing
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{{ url_for('purchasing.index') }}">Purchasing</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('purchasing.purchase_orders') }}">Purchase Orders</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{{ url_for('purchasing.vendors') }}">Vendors</a></li>
                      <li><a class="dropdown-item" href="#">Explore Stock</a></li>
                    </ul>
                </li>

            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>


{% endblock navbar %}




{% block main %}
<div class="container-lg">
    <div class="card">
        <div class="card-body">
            This is some text within a card body.
        </div>
    </div>
</div>
<br>
<div class="container-lg" >
    <div class="card">
        <div class="card-header">
        Featured
        </div>
        <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            {% for f in elements['feed'] %}
                {% for i in f%}
                    <p class="card-text">{{ i.id }}</p>
                {% endfor %}
            {% endfor %}
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
</div>
{% endblock main %}