backend/src/backend/blueprints/purchasing/views.py
from flask import Blueprint, redirect, render_template, url_for
from ...models.models import db 
from ...models.models import (
    Vendor,
    ProductCategory,
)

from ...utils.feed import filter_by_date

purchasing = Blueprint('purchasing', __name__, template_folder="templates/purchasing", url_prefix="/purchasing")

@purchasing.route("/")
def index():
    return render_template("index.html")


@purchasing.route("/vendors")
def vendors():
    elements = {'title': 'Vendors'}
    return render_template('vendors.html', elements=elements,
                vendors=db.session.scalars(db.select(Vendor)).all())


@purchasing.route("/")
def purchase_orders():
    return render_template("purchase_orders.html")

backend/src/backend/blueprints/purchasing/templates/purchasing/purchasing.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
        {% if elements['title'] %}
            <title>{{ elements['title'] }}</title>
        {% else %}
            <title>United-Journal</title>
        {% endif %}
    </head>
    <body>
        <header>
            {% block navbar %} {% endblock navbar %}
        </header>

        <br>

        <main  style="height: 100vh;">
            {% block main %} {% endblock main %}
        </main>
        
        
        <br></br>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <p>&copy; 2023 Logan Lee Development Inc. All rights reserved.</p>
                    </div>
                </div>
            </div>
        </footer>
    </body>


</html>

backend/src/backend/blueprints/purchasing/templates/purchasing/vendors.html
    {% extends 'purchasing.html' %}

    {% block navbar %}
    <nav class="navbar navbar-expand-lg color">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('sales.home') }}">United-Journal</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('purchasing.index') }}">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/reports">Orders</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/about">Purchase-Orders</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/contact">Customers</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('purchasing.vendors') }}">Vendors</a>
                    </li>

                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    {% endblock navbar %}




    {% block main %}
    <div class="container-lg">
        <div class="card">
            <div class="card-body">
                This is some text within a card body.
            </div>
        </div>
    </div>
    <br>
    <div class="container-lg" >
        <div class="card">
            <div class="card-header">
            Featured
            </div>
            <div class="card-body">
                <h5 class="card-title">Our Vendors</h5>
                {% for v in vendors %}
                    <p class="card-text">{{ v.vendor }}</p>
                {% endfor %}
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
    {% endblock main %}